import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Quicksand } from "next/font/google";
import LayoutWrapper from "./components/LayoutWrapper";
const quickSand = Quicksand({
  subsets : ['latin']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body className={`relative flex flex-col min-h-screen antialiased ${quickSand.className}`}>
        <LayoutWrapper>
        <main className="flex-1">{children}</main>
        </LayoutWrapper>
      </body>
    </html>
  );
}
